spring.application.name=notification

logging.level.root=INFO

# APPROACH A: Specify a custom file name and path
logging.file.name=C://notification//logs//notification.log

# APPROACH B: Specify just the directory (creates "spring.log" inside it)
# logging.file.path=C://notification//logs
