spring.application.name=notification

logging.level.root=INFO

# APPROACH A: Specify a custom file name and path
logging.file.name=C://notification//logs//notification.log

# APPROACH B: Specify just the directory (creates "spring.log" inside it)
#logging.file.path=C://notification//logs

#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html

# Disable default whitelabel error view forcing the container to use our error templates
server.error.whitelabel.enabled=false

# Set user name and password for authentication
spring.security.user.name=test
spring.security.user.password=test

################################################################################################
# Spring Actuator configuration
# Expose specific endpoints (Recommended for safety)
management.endpoints.web.exposure.include=health,info,metrics

# OR expose all endpoints (Useful for local development, avoid in production)
# management.endpoints.web.exposure.include=*

# Optional: Add metadata for the /actuator/info endpoint
info.app.name=notification Spring Boot Application
info.app.version=1.0.0
management.info.env.enabled=true
################################################################################################
